services:
  icecast2:
    image: moul/icecast
    container_name: icecast2
    restart: always
    ports:
      - 8002:8000
    environment:
      - ICECAST_HOSTNAME=stream.radio2.life
    env_file: ./secrets.env
