services:
  icecast2:
    image: pltnk/icecast2
    container_name: icecast2
    restart: always
    ports:
      - 8002:8000
    volumes:
      - type: bind
        source: ./icecast.xml
        target: /etc/icecast2/icecast.xml
